//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollatorCAM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ACC_Y_MAN {
            get {
                return ((string)(this["ACC_Y_MAN"]));
            }
            set {
                this["ACC_Y_MAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DEC_Y_MAN {
            get {
                return ((string)(this["DEC_Y_MAN"]));
            }
            set {
                this["DEC_Y_MAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ManSpdSave {
            get {
                return ((int)(this["ManSpdSave"]));
            }
            set {
                this["ManSpdSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CollatorSave {
            get {
                return ((bool)(this["CollatorSave"]));
            }
            set {
                this["CollatorSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Port {
            get {
                return ((string)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IP {
            get {
                return ((string)(this["IP"]));
            }
            set {
                this["IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeedX1 {
            get {
                return ((string)(this["SpeedX1"]));
            }
            set {
                this["SpeedX1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeedX2 {
            get {
                return ((string)(this["SpeedX2"]));
            }
            set {
                this["SpeedX2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeedY1 {
            get {
                return ((string)(this["SpeedY1"]));
            }
            set {
                this["SpeedY1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SpeedY2 {
            get {
                return ((string)(this["SpeedY2"]));
            }
            set {
                this["SpeedY2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SpeedPERC {
            get {
                return ((int)(this["SpeedPERC"]));
            }
            set {
                this["SpeedPERC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SPEED_Y_MAN {
            get {
                return ((int)(this["SPEED_Y_MAN"]));
            }
            set {
                this["SPEED_Y_MAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RailcartSave {
            get {
                return ((bool)(this["RailcartSave"]));
            }
            set {
                this["RailcartSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS1 {
            get {
                return ((string)(this["POS1"]));
            }
            set {
                this["POS1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS2 {
            get {
                return ((string)(this["POS2"]));
            }
            set {
                this["POS2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string POS3 {
            get {
                return ((string)(this["POS3"]));
            }
            set {
                this["POS3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GrabTMR {
            get {
                return ((string)(this["GrabTMR"]));
            }
            set {
                this["GrabTMR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ScanTMR {
            get {
                return ((string)(this["ScanTMR"]));
            }
            set {
                this["ScanTMR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReleaseTMR {
            get {
                return ((string)(this["ReleaseTMR"]));
            }
            set {
                this["ReleaseTMR"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\\Database1.mdf" +
            ";Integrated Security=True")]
        public string Database1ConnectionString {
            get {
                return ((string)(this["Database1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string tesPath {
            get {
                return ((string)(this["tesPath"]));
            }
            set {
                this["tesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Height {
            get {
                return ((string)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryAutoContrast {
            get {
                return ((bool)(this["JanuaryAutoContrast"]));
            }
            set {
                this["JanuaryAutoContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryBlur {
            get {
                return ((bool)(this["JanuaryBlur"]));
            }
            set {
                this["JanuaryBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryAutoContrast {
            get {
                return ((bool)(this["FebruaryAutoContrast"]));
            }
            set {
                this["FebruaryAutoContrast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryBlur {
            get {
                return ((bool)(this["FebruaryBlur"]));
            }
            set {
                this["FebruaryBlur"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryCaptureFromCamera {
            get {
                return ((bool)(this["JanuaryCaptureFromCamera"]));
            }
            set {
                this["JanuaryCaptureFromCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int JanuaryCameraResolution {
            get {
                return ((int)(this["JanuaryCameraResolution"]));
            }
            set {
                this["JanuaryCameraResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryAdaptiveThreshold {
            get {
                return ((decimal)(this["JanuaryAdaptiveThreshold"]));
            }
            set {
                this["JanuaryAdaptiveThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryNoizeFilter {
            get {
                return ((bool)(this["JanuaryNoizeFilter"]));
            }
            set {
                this["JanuaryNoizeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryShowAngle {
            get {
                return ((bool)(this["JanuaryShowAngle"]));
            }
            set {
                this["JanuaryShowAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryShowContours {
            get {
                return ((bool)(this["JanuaryShowContours"]));
            }
            set {
                this["JanuaryShowContours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMinContourLength {
            get {
                return ((decimal)(this["JanuaryMinContourLength"]));
            }
            set {
                this["JanuaryMinContourLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMinContourArea {
            get {
                return ((decimal)(this["JanuaryMinContourArea"]));
            }
            set {
                this["JanuaryMinContourArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryNoizeInt {
            get {
                return ((decimal)(this["JanuaryNoizeInt"]));
            }
            set {
                this["JanuaryNoizeInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryNoizeFilt {
            get {
                return ((bool)(this["JanuaryNoizeFilt"]));
            }
            set {
                this["JanuaryNoizeFilt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMaxACF {
            get {
                return ((decimal)(this["JanuaryMaxACF"]));
            }
            set {
                this["JanuaryMaxACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMinACF {
            get {
                return ((decimal)(this["JanuaryMinACF"]));
            }
            set {
                this["JanuaryMinACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryAllowAngles {
            get {
                return ((bool)(this["JanuaryAllowAngles"]));
            }
            set {
                this["JanuaryAllowAngles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string JanuaryTemplateFile {
            get {
                return ((string)(this["JanuaryTemplateFile"]));
            }
            set {
                this["JanuaryTemplateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FebruaryTemplateFile {
            get {
                return ((string)(this["FebruaryTemplateFile"]));
            }
            set {
                this["FebruaryTemplateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryAdaptiveThreshold {
            get {
                return ((decimal)(this["FebruaryAdaptiveThreshold"]));
            }
            set {
                this["FebruaryAdaptiveThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryAllowAngles {
            get {
                return ((bool)(this["FebruaryAllowAngles"]));
            }
            set {
                this["FebruaryAllowAngles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FebruaryCameraResolution {
            get {
                return ((int)(this["FebruaryCameraResolution"]));
            }
            set {
                this["FebruaryCameraResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryCaptureFromCamera {
            get {
                return ((bool)(this["FebruaryCaptureFromCamera"]));
            }
            set {
                this["FebruaryCaptureFromCamera"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMaxACF {
            get {
                return ((decimal)(this["FebruaryMaxACF"]));
            }
            set {
                this["FebruaryMaxACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMinACF {
            get {
                return ((decimal)(this["FebruaryMinACF"]));
            }
            set {
                this["FebruaryMinACF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMinContourArea {
            get {
                return ((decimal)(this["FebruaryMinContourArea"]));
            }
            set {
                this["FebruaryMinContourArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMinContourLength {
            get {
                return ((decimal)(this["FebruaryMinContourLength"]));
            }
            set {
                this["FebruaryMinContourLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryNoizeFilt {
            get {
                return ((bool)(this["FebruaryNoizeFilt"]));
            }
            set {
                this["FebruaryNoizeFilt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryNoizeFilter {
            get {
                return ((bool)(this["FebruaryNoizeFilter"]));
            }
            set {
                this["FebruaryNoizeFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryNoizeInt {
            get {
                return ((decimal)(this["FebruaryNoizeInt"]));
            }
            set {
                this["FebruaryNoizeInt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryShowAngle {
            get {
                return ((bool)(this["FebruaryShowAngle"]));
            }
            set {
                this["FebruaryShowAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryShowContours {
            get {
                return ((bool)(this["FebruaryShowContours"]));
            }
            set {
                this["FebruaryShowContours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryShowBinarized {
            get {
                return ((bool)(this["JanuaryShowBinarized"]));
            }
            set {
                this["JanuaryShowBinarized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryShowBinarized {
            get {
                return ((bool)(this["FebruaryShowBinarized"]));
            }
            set {
                this["FebruaryShowBinarized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool JanuaryCycleCapture {
            get {
                return ((bool)(this["JanuaryCycleCapture"]));
            }
            set {
                this["JanuaryCycleCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FebruaryCycleCapture {
            get {
                return ((bool)(this["FebruaryCycleCapture"]));
            }
            set {
                this["FebruaryCycleCapture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryAdaptiveThBlockSize {
            get {
                return ((decimal)(this["JanuaryAdaptiveThBlockSize"]));
            }
            set {
                this["JanuaryAdaptiveThBlockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMinDefinition {
            get {
                return ((decimal)(this["JanuaryMinDefinition"]));
            }
            set {
                this["JanuaryMinDefinition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal JanuaryMinICF {
            get {
                return ((decimal)(this["JanuaryMinICF"]));
            }
            set {
                this["JanuaryMinICF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryAdaptiveThBlockSize {
            get {
                return ((decimal)(this["FebruaryAdaptiveThBlockSize"]));
            }
            set {
                this["FebruaryAdaptiveThBlockSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMinDefinition {
            get {
                return ((decimal)(this["FebruaryMinDefinition"]));
            }
            set {
                this["FebruaryMinDefinition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal FebruaryMinICF {
            get {
                return ((decimal)(this["FebruaryMinICF"]));
            }
            set {
                this["FebruaryMinICF"] = value;
            }
        }
    }
}
